# Perceptron Network

In [1]:
import torch
import torch.nn as nn

In [2]:
model = nn.Linear(3,1)

In [4]:
model.weight, model.bias

(Parameter containing:
 tensor([[ 0.1504,  0.1366, -0.5232]], requires_grad=True),
 Parameter containing:
 tensor([-0.5768], requires_grad=True))

In [6]:
input = torch.tensor([1,2,3],dtype = torch.float32)

In [8]:
output = model(input)
output

tensor([-1.7227], grad_fn=<AddBackward0>)

In [15]:
# wX + b =>verify
print((input.numpy()*model.weight.detach().numpy()).sum() + model.bias)

tensor([-1.7227], grad_fn=<AddBackward0>)
